# Use root/example as user/password credentials
version: '3.8'

services:

  # webservice:
  #   container_name: go_app
  #   depends_on:
  #     - db # must start database first
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./
  #   env_file:
  #     - dev.env
  #   ports:
  #     - ${GO_LOCAL_PORT}:${GO_DOCKER_PORT}
  #   volumes:
  #     - .:/usr/src/app
  #   command: air cmd/main.go -b 0.0.0.0

  db:
    container_name: db_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_LOCAL_PORT}:${DB_DOCKER_PORT}
    volumes:
      - mysqlvol:/var/lib/mysql

volumes:
  mysqlvol:
