// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginResponse struct {
	AccessToken *string `json:"access_token"`
	Exp         *string `json:"exp"`
}

type MutationResponse struct {
	Code int `json:"code"`
	// Indicates whether the mutation was successful
	Success bool `json:"success"`
	// Human-readable message for the UI
	Message string `json:"message"`
	// Newly updated result after a successful mutation
	Result int64 `json:"result"`
}
